rm -rf /usr/local/bin/tint2
rm -rf /usr/local/share/icons/hicolor/scalable/apps/tint2.svg
rm -rf /usr/local/share/applications/tint2.desktop
rm -rf /etc/xdg/tint2/tint2rc
rm -rf /usr/local/share/tint2/default_icon.png
rm -rf /usr/local/share/doc/tint2/AUTHORS
rm -rf /usr/local/share/doc/tint2/ChangeLog
rm -rf /usr/local/share/doc/tint2/README.md
rm -rf /usr/local/share/man/man1/tint2.1
rm -rf /usr/local/bin/tint2conf
rm -rf /usr/local/share/icons/hicolor/scalable/apps/tint2conf.svg
rm -rf /usr/local/share/applications/tint2conf.desktop
rm -rf /usr/local/share/locale/pl/LC_MESSAGES/tint2conf.mo
rm -rf /usr/local/share/locale/ru/LC_MESSAGES/tint2conf.mo
rm -rf /usr/local/share/locale/bs/LC_MESSAGES/tint2conf.mo
rm -rf /usr/local/share/locale/hr/LC_MESSAGES/tint2conf.mo
rm -rf /usr/local/share/locale/sr/LC_MESSAGES/tint2conf.mo
rm -rf /usr/local/share/locale/fr/LC_MESSAGES/tint2conf.mo
rm -rf /usr/local/share/tint2/icon_and_text_3.tint2rc
rm -rf /usr/local/share/tint2/text_only_5.tint2rc
rm -rf /usr/local/share/tint2/text_only_3.tint2rc
rm -rf /usr/local/share/tint2/icon_and_text_1.tint2rc
rm -rf /usr/local/share/tint2/vertical-dark-transparent.tint2rc
rm -rf /usr/local/share/tint2/horizontal-light-opaque.tint2rc
rm -rf /usr/local/share/tint2/icon_and_text_4.tint2rc
rm -rf /usr/local/share/tint2/text_only_4.tint2rc
rm -rf /usr/local/share/tint2/text_only_1.tint2rc
rm -rf /usr/local/share/tint2/horizontal-dark-transparent.tint2rc
rm -rf /usr/local/share/tint2/vertical-light-transparent.tint2rc
rm -rf /usr/local/share/tint2/icon_only_2.tint2rc
rm -rf /usr/local/share/tint2/icon_only_6.tint2rc
rm -rf /usr/local/share/tint2/text_only_2.tint2rc
rm -rf /usr/local/share/tint2/horizontal-dark-opaque.tint2rc
rm -rf /usr/local/share/tint2/text_only_6.tint2rc
rm -rf /usr/local/share/tint2/icon_and_text_2.tint2rc
rm -rf /usr/local/share/tint2/icon_only_4.tint2rc
rm -rf /usr/local/share/tint2/icon_only_3.tint2rc
rm -rf /usr/local/share/tint2/horizontal-light-transparent.tint2rc
rm -rf /usr/local/share/tint2/icon_only_1.tint2rc
rm -rf /usr/local/share/tint2/icon_only_7.tint2rc
rm -rf /usr/local/share/tint2/vertical-neutral-icons.tint2rc
rm -rf /usr/local/share/tint2/vertical-light-opaque.tint2rc
rm -rf /usr/local/share/tint2/vertical-dark-opaque.tint2rc
